#!/usr/bin/env bash
#
# Measures how each fetch strategy scales as the table grows, and writes results/results.md.
#
# The page size never changes -- only the number of rows in the table. That is the whole
# question: a listing endpoint's cost should depend on the page you asked for, not on how long
# the customer has been a customer.

set -euo pipefail

KEYCLOAK_PORT="${KEYCLOAK_PORT:-18180}"
ORDERS_PORT="${ORDERS_PORT:-8081}"
ORDERS="http://localhost:${ORDERS_PORT}"
PAGE_SIZE="${PAGE_SIZE:-20}"
STEPS="${STEPS:-250 250 500 1000 2000}"
REPEATS="${REPEATS:-5}"

OUT_DIR="$(dirname "$0")/results"
OUT="${OUT_DIR}/results.md"
mkdir -p "$OUT_DIR"

TOKEN=$(curl -sS -X POST "http://localhost:${KEYCLOAK_PORT}/realms/platform/protocol/openid-connect/token" \
  -d "client_id=platform-cli" -d "username=alice" -d "password=alice" -d "grant_type=password" \
  | python3 -c "import sys,json;print(json.load(sys.stdin)['access_token'])")

measure() { # strategy -> "statements rows median_ms"
  local strategy="$1"
  for _ in $(seq 1 "$REPEATS"); do
    curl -sS -H "Authorization: Bearer ${TOKEN}" \
      "${ORDERS}/api/orders?strategy=${strategy}&page=0&size=${PAGE_SIZE}" \
      | python3 -c "import sys,json;d=json.load(sys.stdin);print(d['jdbcStatements'],d['rowsMaterialised'],d['elapsedMillis'])"
  done | python3 -c "
import sys
rows=[l.split() for l in sys.stdin]
ms=sorted(int(r[2]) for r in rows)
print(rows[-1][0], rows[-1][1], ms[len(ms)//2])
"
}

{
  echo "# Fetch strategy scaling"
  echo
  echo "Generated by \`bench.sh\` on $(date -u '+%Y-%m-%d %H:%M UTC')."
  echo "Page size ${PAGE_SIZE} throughout; only the table size changes."
  echo "Median of ${REPEATS} runs, after a warm-up request."
  echo
  echo "| Orders in tenant | Strategy | JDBC statements | Rows materialised | Median ms |"
  echo "|---:|---|---:|---:|---:|"
} > "$OUT"

TOTAL=0
echo "Seeding and measuring. This takes a couple of minutes."

for step in $STEPS; do
  curl -sS -X POST -H "Authorization: Bearer ${TOKEN}" \
    "${ORDERS}/api/admin/seed?orders=${step}&linesPerOrder=8" > /dev/null
  TOTAL=$((TOTAL + step))

  # Warm-up: the first call after a seed pays for a cold page cache and JIT.
  curl -sS -H "Authorization: Bearer ${TOKEN}" \
    "${ORDERS}/api/orders?strategy=TWO_QUERY&size=${PAGE_SIZE}" > /dev/null

  printf '  %5d orders: ' "$TOTAL"
  for strategy in NAIVE JOIN_FETCH TWO_QUERY; do
    read -r stmts rows ms <<< "$(measure "$strategy")"
    printf '%s(%sms) ' "$strategy" "$ms"
    echo "| ${TOTAL} | ${strategy} | ${stmts} | ${rows} | ${ms} |" >> "$OUT"
  done
  printf '\n'
done

{
  echo
  echo "## Reading this"
  echo
  echo "- **NAIVE** holds its statement count at page size + 2 and its row count flat, but pays"
  echo "  a network round trip per row. It degrades with *latency*, not with table size, which"
  echo "  is why it often looks acceptable on a laptop with the database on localhost and falls"
  echo "  apart against a database one availability zone away."
  echo "- **JOIN_FETCH** issues two statements at any size — and materialises the entire table"
  echo "  into the persistence context to serve twenty rows. This is the strategy that looks"
  echo "  like the fix."
  echo "- **TWO_QUERY** is flat on every axis: three statements, one page of rows, whatever the"
  echo "  table holds."
} >> "$OUT"

echo
echo "Wrote ${OUT}"
